spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 1
      maximumPoolSize: 4

server:
  port: 8080

logging:
  level:
    root: INFO

---

spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
